apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::846902660646:role/aws-prometheus"  # Replace account_id when deploying
